---
- name: Creare file htpasswd per il registry
  community.general.htpasswd:
    path: /tmp/registry_htpasswd
    name: "{{ registry_user }}"
    password: "{{ registry_password }}"
    crypt_scheme: bcrypt

- name: Avviare registry Docker locale con autenticazione
  docker_container:
    name: "{{ registry_name }}"
    image: registry:2
    state: started
    ports:
      - "{{ registry_port }}:5000"
    restart_policy: always
    volumes:
      - /tmp/registry_htpasswd:/auth/htpasswd:ro
    env:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"

- name: Login al registry locale
  community.docker.docker_login:
    registry_url: "localhost:{{ registry_port }}"
    username: "{{ registry_user }}"
    password: "{{ registry_password }}"

