---
- name: Leggere chiave pubblica SSH
  slurp:
    src: "{{ playbook_dir }}/.ssh/id_rsa.pub"
  register: ssh_key_content

- name: Build containers con SSH
  community.docker.docker_image:
    name: "{{ item.tag }}"
    source: build
    build:
      path: "{{ item.context }}"
      dockerfile: Dockerfile
      args:
        SSH_PUB_KEY: "{{ ssh_key_content.content | b64decode }}"
        SSH_PASSWORD: "{{ ssh_password }}"  # variabile dal Vault
    state: present
  loop: "{{ containers }}"

